### ISSUE TITLE
Unable to start the plug-in

### ISSUE THREAD

**Issue by aml2023529** [HaHaWTH/AuthMeReReloaded#44]
### What behaviour is observed?

Suddenly the plugin won't start

### Expected behaviour

1

### To Reproduce

1

### Plugin list

> pl
[00:38:25 INFO]: Paper Plugins: (1):
[00:38:25 INFO]:  - EconomyShopGUI-Premium
[00:38:25 INFO]: Bukkit Plugins: (42):
[00:38:25 INFO]:  - AdvancedEnchantments, AuthMe, ChestProtect, Chunky, Citizens, CMI, *CMIEInjector, CMILib, CoreProtect, EvenMoreFish
[00:38:25 INFO]:  ExoticGarden, *FHelper, FluffyMachines, GuizhanLibPlugin, ItemsAdder, LiteXpansion, LoneLibs, LuckPerms, MMOCore, MMOItems
[00:38:25 INFO]:  Multiverse-Core, MythicLib, MythicMobs, Pl-Hide-Pro, PlaceholderAPI, PlayerPoints, PlayerTitle, PlotSquared, PlugManX, ProtocolLib
[00:38:25 INFO]:  PvPManager, QuickShop-Hikari, Residence, Shopkeepers, Slimefun, SlimeGlue, spark, TAB, TrMenu, Vault
[00:38:25 INFO]:  Vulcan, WorldEdit

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

> authme version [00:44:28 WARN]: Unexpected exception while parsing console command "authme version" org.bukkit.command.CommandException: Cannot execute command 'authme' in plugin AuthMe v5.6.0-FORK-b30 - plugin is disabled.         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:986) ~[purpur-1.20.1.jar:git-Purpur-2062]         at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.20.1.jar:git-Purpur-2062]         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2062]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Error log (if applicable)

https://gist.github.com/aml2023529/4a99e28efedeac0a899f461a5294cadf

### Configuration

1

**Comment by HaHaWTH** [comment]
It seems that your language file is not loaded correctly, is it the new generated one?
