### ISSUE TITLE
Incompatible Java version

### ISSUE THREAD

**Issue by 3328429240** [HaHaWTH/AuthMeReReloaded#50]
### What behaviour is observed?

[03:35:44] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-FORK-b30
[03:35:44] [Server thread/INFO]: [AuthMe] You are running an unofficial fork version of AuthMe!
[03:35:45] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [UnsupportedClassVersionError]: JVMCFRE003 主要版本错误；类=fr/xephi/authme/libs/com/zaxxer/hikari/HikariDataSource，偏移量=6
[03:35:45] [Server thread/WARN]: java.lang.UnsupportedClassVersionError: JVMCFRE003 主要版本错误；类=fr/xephi/authme/libs/com/zaxxer/hikari/HikariDataSource，偏移量=6
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.defineClassImpl(Native Method)
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
[03:35:45] [Server thread/WARN]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[03:35:45] [Server thread/WARN]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
[03:35:45] [Server thread/WARN]: 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
[03:35:45] [Server thread/WARN]: 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
[03:35:45] [Server thread/WARN]: 	at java.security.AccessController.doPrivileged(AccessController.java:774)
[03:35:45] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
[03:35:45] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.datasource.MySQL.setConnectionArguments(MySQL.java:130)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:62)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:68)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:50)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:309)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:285)
[03:35:45] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:159)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[03:35:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[03:35:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[03:35:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[03:35:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[03:35:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[03:35:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[03:35:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:823)
[03:35:45] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[03:35:45] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-FORK-b30 is unloaded successfully!

### Expected behaviour

修复此问题，使得Java8可以使用MySQL存储数据
Fix this issue so that Java8 can use MySQL to store data

### To Reproduce

当将存储方式设置为MySQL将会出现此情况
This situation will occur when the storage method is set to MySQL

### Plugin list

authme

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

5.6.0-FORK-b31

### Error log (if applicable)

37fb86a773c04ae587938b5f2d8c1da3

### Configuration

backend: Mysql

**Comment by HaHaWTH** [comment]
Will this occur on original AuthMe or only on my fork version?

**Comment by HaHaWTH** [comment]
麻烦再试下原版Authme会不会有这问题，我这边没MySQL的环境，感谢感谢

**Comment by HaHaWTH** [comment]
你用的是Legacy版本还是正常的嘞

**Comment by HaHaWTH** [comment]
就是说你下载原版authme是legacy还是正常版本

**Comment by HaHaWTH** [comment]
已修复，重新下载b31版本即可，麻烦给个star谢谢惹

**Comment by HaHaWTH** [comment]
Released in b32
